LoadTTF('boss_name', 'assets/font/SourceHanSansCN-Bold.otf', 20)
LoadTTF('sc_name', 'assets/font/SourceHanSerifCN-Heavy.otf', 26)
LoadTTF('sc_pr', 'assets/font/SourceHanSansCN-Bold.otf', 30)
LoadTTF('dialog', 'assets/font/SourceHanSansCN-Bold.otf', 30)
LoadTTF('menuttf', 'assets/font/SourceHanSansCN-Bold.otf', 20)

LoadFont('score', 'THlib/UI/font/score_new.fnt', false)
LoadFont('item', 'THlib/UI/font/item.fnt', true)
LoadFont('menu', 'THlib/UI/font/menu.fnt', false)
LoadFont('bonus', 'THlib/UI/font/bonus.fnt', true)
LoadFont('score1', 'THlib/UI/font/score_new.fnt', false)
LoadFont('score2', 'THlib/UI/font/score_new.fnt', false)
LoadFont('score3', 'THlib/UI/font/score_new_score.fnt', false)
LoadFont('time', 'THlib/UI/font/score_new_score.fnt', true)
LoadFont('replay', 'THlib/UI/font/replay.fnt', false)
